#!/usr/bin/env python3
"""
migrate.py - Safe file reorganization with full safety features
Executes migration plans generated by restructure_planner.py
"""

import os
import json
import shutil
import re
import argparse
from pathlib import Path
from typing import Dict, List, Set
import sys

# Import safety manager
sys.path.insert(0, str(Path(__file__).parent))
from safety_manager import SafetyManager

class MigrationExecutor:
    """
    Execute codebase migrations safely with:
    - Automatic backups
    - Dry-run mode
    - Import path updates
    - Rollback capability
    - Git integration
    """

    def __init__(self, root_path: str, plan_path: str, safety_manager: SafetyManager):
        self.root_path = Path(root_path).resolve()
        self.plan_path = Path(plan_path)
        self.safety = safety_manager
        self.plan = self._load_plan()
        self.import_updates = {}
        self.moved_files = []

    def _load_plan(self) -> Dict:
        """Load migration plan from JSON file"""
        if not self.plan_path.exists():
            raise FileNotFoundError(f"Migration plan not found: {self.plan_path}")

        with open(self.plan_path, 'r') as f:
            return json.load(f)

    def execute_migration(self, dry_run: bool = False, skip_backup: bool = False) -> bool:
        """
        Execute migration plan

        Args:
            dry_run: Preview changes without executing
            skip_backup: Skip automatic backup (not recommended)

        Returns:
            True if successful
        """
        print("=" * 60)
        print("🚀 CODEBASE MIGRATION")
        print("=" * 60)
        print(f"\nPattern: {self.plan['pattern']}")
        print(f"Root: {self.root_path}")
        print(f"Mode: {'DRY RUN' if dry_run else 'EXECUTE'}\n")

        if dry_run:
            print("🔍 DRY RUN MODE - No changes will be made\n")
        else:
            # Safety checks
            if not skip_backup:
                print("🔒 Creating safety backup...")
                backup_path = self.safety.create_backup(
                    f"Pre-migration backup: {self.plan['pattern']}"
                )
                print(f"✅ Backup created: {backup_path}\n")

            # Git pre-operation commit
            git_commit = self.safety.git_pre_operation_commit(
                f"migration to {self.plan['pattern']}"
            )
            if git_commit:
                print(f"✅ Git commit: {git_commit[:7]}\n")

        # Execute migration phases
        for step in self.plan.get('steps', []):
            phase = step.get('phase')
            order = step.get('order')
            description = step.get('description')

            print(f"📌 Phase {order}: {description}")

            if phase == 'preparation':
                self._execute_preparation(step, dry_run)
            elif phase == 'structure':
                self._execute_structure(step, dry_run)
            elif phase == 'migration':
                self._execute_file_moves(step, dry_run)
            elif phase == 'imports':
                self._execute_import_updates(step, dry_run)
            elif phase == 'cleanup':
                self._execute_cleanup(step, dry_run)

            print()

        # Summary
        print("=" * 60)
        if dry_run:
            print("✅ DRY RUN COMPLETE")
        else:
            print("✅ MIGRATION COMPLETE")
        print("=" * 60)

        if not dry_run:
            print(f"\nFiles moved: {len(self.moved_files)}")
            print(f"Imports updated: {len(self.import_updates)}")

            # Save migration log
            self._save_migration_log()

            print("\n💡 Next steps:")
            print("  1. Run tests to verify nothing broke")
            print("  2. Commit changes with: git add -A && git commit")
            print("  3. If issues occur, restore from backup")

        return True

    def _execute_preparation(self, step: Dict, dry_run: bool):
        """Execute preparation tasks"""
        tasks = step.get('tasks', [])
        for task in tasks:
            if dry_run:
                print(f"  ✓ Would: {task}")
            else:
                print(f"  ℹ️  {task}")

    def _execute_structure(self, step: Dict, dry_run: bool):
        """Create new directory structure"""
        tasks = step.get('tasks', [])
        for task in tasks:
            # Extract directory path from task
            if 'Create directory:' in task:
                dir_path = task.replace('Create directory:', '').strip()
                full_path = self.root_path / dir_path

                if dry_run:
                    print(f"  ✓ Would create: {dir_path}")
                else:
                    full_path.mkdir(parents=True, exist_ok=True)
                    print(f"  ✅ Created: {dir_path}")

    def _execute_file_moves(self, step: Dict, dry_run: bool):
        """Execute file move operations"""
        tasks = step.get('tasks', [])
        total_moves = step.get('total_moves', len(tasks))

        print(f"  Moving {total_moves} files...")

        for task in tasks:
            # Parse move task (format: "Move source to destination")
            if 'Move ' in task and ' to ' in task:
                parts = task.replace('Move ', '').split(' to ')
                if len(parts) == 2:
                    source_path = self.root_path / parts[0].strip()
                    dest_path = self.root_path / parts[1].strip()

                    if dry_run:
                        print(f"    ✓ {parts[0]} → {parts[1]}")
                    else:
                        if source_path.exists():
                            # Create destination directory
                            dest_path.parent.mkdir(parents=True, exist_ok=True)

                            # Move file
                            shutil.move(str(source_path), str(dest_path))

                            # Track for import updates
                            self.moved_files.append({
                                'source': str(source_path),
                                'destination': str(dest_path)
                            })

                            # Update import map
                            self._register_import_update(source_path, dest_path)

    def _execute_import_updates(self, step: Dict, dry_run: bool):
        """Update import statements after file moves"""
        if not self.import_updates:
            print("  No import updates needed")
            return

        print(f"  Updating imports in {len(self.import_updates)} files...")

        for file_path, updates in self.import_updates.items():
            if dry_run:
                print(f"    ✓ Would update: {file_path}")
            else:
                self._update_file_imports(file_path, updates)
                print(f"    ✅ Updated: {file_path}")

    def _execute_cleanup(self, step: Dict, dry_run: bool):
        """Clean up empty directories"""
        if dry_run:
            print("  ✓ Would remove empty directories")
        else:
            self._remove_empty_dirs()
            print("  ✅ Removed empty directories")

    def _register_import_update(self, old_path: Path, new_path: Path):
        """Register that imports from old_path should now import from new_path"""
        old_relative = old_path.relative_to(self.root_path)
        new_relative = new_path.relative_to(self.root_path)

        # Store mapping for import updates
        old_import = str(old_relative).replace('.tsx', '').replace('.ts', '').replace('.jsx', '').replace('.js', '').replace('/', '.')
        new_import = str(new_relative).replace('.tsx', '').replace('.ts', '').replace('.jsx', '').replace('.js', '').replace('/', '.')

        # Find all files that might import this file
        for file_path in self.root_path.rglob('*.ts*'):
            if file_path.is_file() and file_path != new_path:
                rel_path = str(file_path.relative_to(self.root_path))
                if rel_path not in self.import_updates:
                    self.import_updates[rel_path] = []

                self.import_updates[rel_path].append({
                    'old': old_relative,
                    'new': new_relative
                })

    def _update_file_imports(self, file_path: str, updates: List[Dict]):
        """Update import statements in a file"""
        full_path = self.root_path / file_path

        if not full_path.exists():
            return

        with open(full_path, 'r') as f:
            content = f.read()

        original_content = content

        for update in updates:
            old_path = update['old']
            new_path = update['new']

            # Update various import formats
            # import { X } from './old/path'
            # import X from './old/path'
            # const X = require('./old/path')

            old_import = str(old_path).replace('.tsx', '').replace('.ts', '').replace('.jsx', '').replace('.js', '')
            new_import = str(new_path).replace('.tsx', '').replace('.ts', '').replace('.jsx', '').replace('.js', '')

            # Pattern for ES6 imports
            patterns = [
                (rf'from\s+[\'"]\.\/({re.escape(old_import)})[\'"]', f"from './{new_import}'"),
                (rf'from\s+[\'"]\.\.\/({re.escape(old_import)})[\'"]', f"from '../{new_import}'"),
                (rf'require\([\'"]\.\/({re.escape(old_import)})[\'"]\)', f"require('./{new_import}')"),
            ]

            for pattern, replacement in patterns:
                content = re.sub(pattern, replacement, content)

        # Only write if content changed
        if content != original_content:
            with open(full_path, 'w') as f:
                f.write(content)

    def _remove_empty_dirs(self):
        """Remove empty directories after migration"""
        for dirpath, dirnames, filenames in os.walk(self.root_path, topdown=False):
            dir_path = Path(dirpath)

            # Skip safety directory
            if '.codebase-safety' in str(dir_path):
                continue

            # Check if directory is empty
            if not any(dir_path.iterdir()):
                dir_path.rmdir()

    def _save_migration_log(self):
        """Save migration log for rollback purposes"""
        log_file = self.root_path / '.codebase-safety' / 'last_migration.json'

        log_data = {
            'plan': self.plan['pattern'],
            'timestamp': self.safety.operation_log[-1]['timestamp'] if self.safety.operation_log else 'unknown',
            'moved_files': self.moved_files,
            'import_updates': self.import_updates
        }

        with open(log_file, 'w') as f:
            json.dump(log_data, f, indent=2)


def main():
    """CLI interface for migration executor"""
    parser = argparse.ArgumentParser(description='Execute codebase migration')
    parser.add_argument('--root', default='.', help='Project root directory')
    parser.add_argument('--plan', required=True, help='Path to migration plan JSON')
    parser.add_argument('--dry-run', action='store_true', help='Preview changes without executing')
    parser.add_argument('--backup', action='store_true', default=True, help='Create backup before migration')
    parser.add_argument('--no-backup', dest='backup', action='store_false', help='Skip backup (dangerous!)')
    parser.add_argument('--rollback-on-error', action='store_true', help='Automatically rollback if errors occur')

    args = parser.parse_args()

    # Initialize safety manager
    safety = SafetyManager(args.root)

    # Initialize migration executor
    executor = MigrationExecutor(args.root, args.plan, safety)

    try:
        # Execute migration
        success = executor.execute_migration(
            dry_run=args.dry_run,
            skip_backup=not args.backup
        )

        if success:
            sys.exit(0)
        else:
            sys.exit(1)

    except Exception as e:
        print(f"\n❌ Migration failed: {e}")

        if args.rollback_on_error and not args.dry_run:
            print("\n🔄 Rolling back changes...")
            backups = safety.list_backups()
            if backups:
                latest_backup = backups[-1]
                safety.restore_backup(latest_backup['path'])
                print("✅ Rollback complete")

        sys.exit(1)


if __name__ == '__main__':
    main()
